// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CashInfo struct {
	ID      int64          `json:"id"`
	UserID  int64          `json:"user_id"`
	Balance pgtype.Numeric `json:"balance"`
}

type Country struct {
	ID         int64       `json:"id"`
	Name       pgtype.Text `json:"name"`
	Coin       pgtype.Text `json:"coin"`
	CoinSymbol pgtype.Text `json:"coin_symbol"`
}

type Expense struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	Category  string             `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CountryID int64              `json:"country_id"`
}

type MonthExpense struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Currently pgtype.Numeric     `json:"currently"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Wage struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CountryID int64              `json:"country_id"`
}
